# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class CodingLlmMonitor < Formula
  desc "Terminal-based dashboard for monitoring code assistant services"
  homepage "https://github.com/jbarson/Coding-LLM-Monitor"
  version "1.0.9"
  license "MIT"

  on_macos do
    # macOS binaries are universal (work on both Intel and ARM)
    url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.9/coding-llm-monitor-macos"
    sha256 "ec75c0ce26c7cfd7b1bde4e51d9faa869e366802428e729beb3e57fdb4ade812"
  end

  on_linux do
    # Linux binaries work on both Intel and ARM
    url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.9/coding-llm-monitor-linux"
    sha256 "24fa2a965e63a3015a2f7e29eae128cce50c8d329d4091a43609d56c090c5684"
  end

  def install
    if OS.mac?
      bin.install "coding-llm-monitor-macos" => "coding-llm-monitor"
      chmod 0755, bin/"coding-llm-monitor"
    else
      bin.install "coding-llm-monitor-linux" => "coding-llm-monitor"
      chmod 0755, bin/"coding-llm-monitor"
    end
  end

  test do
    # Test that the executable runs (it will show the dashboard)
    assert_match "Coding LLM Status Monitor", shell_output("#{bin}/coding-llm-monitor --help 2>&1", 1) || true
  end
end

