# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew. DO NOT EDIT.
class CodingLlmMonitor < Formula
  desc "Terminal-based dashboard for monitoring code assistant services"
  homepage "https://github.com/jbarson/Coding-LLM-Monitor"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.0/coding-llm-monitor-macos"
      sha256 "PLACEHOLDER_SHA256_INTEL"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.0/coding-llm-monitor-macos"
      sha256 "PLACEHOLDER_SHA256_ARM"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.0/coding-llm-monitor-linux"
      sha256 "PLACEHOLDER_SHA256_LINUX_INTEL"
    end
    if Hardware::CPU.arm?
      url "https://github.com/jbarson/Coding-LLM-Monitor/releases/download/v1.0.0/coding-llm-monitor-linux"
      sha256 "PLACEHOLDER_SHA256_LINUX_ARM"
    end
  end

  def install
    if OS.mac?
      bin.install "coding-llm-monitor-macos" => "coding-llm-monitor"
      chmod 0755, bin/"coding-llm-monitor"
    else
      bin.install "coding-llm-monitor-linux" => "coding-llm-monitor"
      chmod 0755, bin/"coding-llm-monitor"
    end
  end

  test do
    # Test that the executable runs (it will show the dashboard)
    assert_match "Coding LLM Status Monitor", shell_output("#{bin}/coding-llm-monitor --help 2>&1", 1) || true
  end
end

